services:
  server:
    container_name: server
    build:
      context: ./src
      target: final
    ports:
      - 8080:80
    environment:
      db_host: db
      db_user: realuser
      db_password: realpassword
      db_database: shopdb
    depends_on:
      db:
        condition: service_healthy

  db:
    hostname: db
    build: ./database
    container_name: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: realuser
      POSTGRES_PASSWORD: realpassword
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
